### PR TITLE
fix semantic-release setup to follow latest rules

### PR DESCRIPTION
**Pull request by alexkli**
Semantic-release was setup for this repo but it was not working and not following our latest setup with `BUGFIX-RELEASE:` etc. prefixes.

### CODE REVIEW

**Comment by alexkli** [comment]
Let's see if it works :)

**Comment by alexkli** [comment]
Did not: https://travis-ci.com/github/adobe/node-cgroup-metrics/jobs/363544630

Not quite sure what the issue is, but I see these discrepancies:

1. it ran the `release` stage on `Windows` (why?), but we say ` condition:  $TRAVIS_OS_NAME == linux` so it skipped it, doing no release
2. it run `npm run report-coverage` which failed as it did not run `npm test` before (we don't need to report coverage here)

**Comment by alexkli** [comment]
Ok, possible answers:

1. the `.travis.yml` here [listed `windows` before `linux`](https://github.com/adobe/node-cgroup-metrics/blob/3a8cd523ff68ea87430be2a13bb345f2485583e0/.travis.yml#L11-L14), maybe that tells Travis what OS to use for the release/deploy stage

2. this seems to happen everywhere, but get ignored. see here, expand the `npm run report-coverage` part in the logs and see it fails too: https://travis-ci.com/github/adobe/aio-cli-plugin-asset-compute/jobs/363148121
   - maybe we should switch to `after_script` so it doesn't run after deploy (which is where we run the release): https://docs.travis-ci.com/user/job-lifecycle/

**Comment by tmathern** [comment]
Drop the other OS from travis.yml: https://github.com/adobe/node-cgroup-metrics/blob/master/.travis.yml#L12
This will be a start. Also drop https://github.com/adobe/node-cgroup-metrics/blob/master/.travis.yml#L17, we already test 10.15 and 10.19 (should reduce wait times too).

And there seems to be a syntax issue: https://github.com/adobe/node-cgroup-metrics/blob/master/.travis.yml#L39, there should only be one `=` for the test, according to documentation (https://docs.travis-ci.com/user/deployment-v2/conditional)

**Comment by tmathern** [comment]
https://github.com/adobe/node-cgroup-metrics/pull/24

**Comment by alexkli** [comment]
See #25.

**Comment by alexkli** [comment]
#25 mostly worked, and semantic-release was triggered, but now it [failed](https://travis-ci.com/github/adobe/node-cgroup-metrics/jobs/363558344) with `This operation requires a one-time password from your authenticator.` because likely the github token set in travis is old and needs a new one. Will try to update it.

**Comment by alexkli** [comment]
Latest try in #27.

**Comment by alexkli** [comment]
Worked!

**Comment by alexkli** [comment]
Regarding 2. from above: `after_script` did not help, it also runs on the release stage, see https://travis-ci.com/github/adobe/node-cgroup-metrics/jobs/363568375

But it doesn't fail it either, so we can just keep ignoring it. Suggest we stick to `after_success`.

**Pull request merged**
